name: Build the file main.tex in lab03 directory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: create_docker_container
        run: |
          cd lab03
          docker build -t latex_container .

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build latex document
        run: |
          cd lab03
          ./dr.sh "pdflatex main.tex"
          
      - name: Upload pdf file
        uses: actions/upload-artifact@v1
        if: always()
        continue-on-error: true
        with:
          name: main.pdf
          path: lab03/main.pdf
